name: Publish
on:
  # Enable manual run
  workflow_dispatch:
  push:
    tags:
      - "*.*"
env:
  pkg_name: step-builder
jobs:
  create-build:
    name: Create ${{ matrix.target }} build
    runs-on: ${{ matrix.os }}
    # softprops/action-gh-release needs this permission
    permissions:
      contents: write

    strategy:
      # Disable fail-fast as we want results from all even if one fails.
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: linux
            build_path: build/distributions

    steps:
      - name: Install JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '8.10.2'

      # Build the project
      - name: Build and Sign Plugin
        env:
          CERTIFICATE_CHAIN: ${{ secrets.JETBRAINS_CERT_CHAIN }}
          PRIVATE_KEY: ${{ secrets.JETBRAINS_PRIVATE_KEY }}
          PRIVATE_KEY_PASSWORD: ${{ secrets.JETBRAINS_PRIVATE_KEY_PASSWORD }}
        run: ./gradlew clean buildPlugin signPlugin

      - name: Add packaged build to release draft
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: false
          files: build/distributions/*-signed.zip
          token: ${{ secrets.STEP_BUILDER_RELEASE_KEY }}
